name: Pull Request Template Action

on:
  pull_request:
    types: [opened, edited]

jobs:
  generate_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request Template
        run: |
          if [[ "${{ github.event.action }}" == "opened" || "${{ github.event.action }}" == "edited" ]]; then
            PR_TEMPLATE=".github/pull_request_template.md"
            echo "Creating Pull Request Template..."
            echo "## Pull Request Title" > "$PR_TEMPLATE"
            echo "" >> "$PR_TEMPLATE"
            echo "## Description" >> "$PR_TEMPLATE"
            echo "<!-- Please include a summary of the changes and relevant motivation. -->" >> "$PR_TEMPLATE"
            echo "" >> "$PR_TEMPLATE"
            echo "## Related Issue" >> "$PR_TEMPLATE"
            echo "<!-- Please link any related issues here. -->" >> "$PR_TEMPLATE"
            echo "" >> "$PR_TEMPLATE"
            echo "## Checklist" >> "$PR_TEMPLATE"
            echo "- [ ] Code compiles correctly" >> "$PR_TEMPLATE"
            echo "- [ ] Tests have been added/updated" >> "$PR_TEMPLATE"
            echo "- [ ] Documentation has been updated" >> "$PR_TEMPLATE"
          fi
